# Example configuration file.
#
# In order to enable the example configuration settings, simply remove the # symbol
# in front of the setting.
#
# Make sure you read the whole configuration file. Many of the settings at the top
# of the file can (and by default, are) overridden by settings farther down.
# 
# The default configuration is extremely restrictive by default, you may want to
# give your staff members more freedom.

# Debug mode. Prints a lot of information to the server console when set to true.
# Can be used to figure out why your setting aren't working like you expect them
# to. Should be used before reporting any bugs about the software.
debug: false

# Hide players on duty.
hide-on-duty: false

# Duty tool list. When players enter duty mode, their inventory will be saved, and
# they will instead be given this list of items. Setting a slot to AIR or 0 or
# not specifying anything for a slot means they get no item in that slot.
# The items listed can be either material name
# (see http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html for list) or
# material item ID number.
duty-tools:
#  slot-1: 'WOOD_AXE'
#  slot-2: 'WOOD_PICKAXE'
#  slot-3: 'COMPASS'
#  slot-4: 'STRING'
#  slot-5: 'BEDROCK'
#  slot-6: 'AIR'
#  slot-7: 'AIR'
#  slot-8: 'AIR'
#  slot-9: 'AIR'

# This setting switches between exclude mode and include mode. Which mode you should
# choose depends on your style. When include mode is true, the lists below configure
# what is allowed. In other words, anything not explicitly allowed below is disallowed.
# On the other hand, when include mode is false, the opposite is true; anything not
# explicitly disallowed is allowed.
#
# The original DoOdy plug-in only had exclude mode. I lean towards (and wanted) the
# opposite behavior, so my default will be the opposite of DoOdy's only behavior. In
# other words, set this to 'false' to have OnDoOdy behave like DoOdy did.
include-mode: true

# Which world(s) are allowed/disallowed to be on duty in. This can also be set
# per-player by giving them the permission doody.worlds.<worldname>.
worlds:
#  - world
#  - world_nether
#  - world_the_end
#  - other_world

# Which item(s) can/cannot be dropped while on duty. Can be either material name
# (see http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html for list) or
# material item ID number.
drops:
#  - 'STONE'
#  - 'DIRT'
#  - '12' # a.k.a SAND

# Which item(s) can/cannot be picked up while on duty. Can be either material name
# (see http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html for list) or
# material item ID number.
pickups:
#  - 'STONE'
#  - 'DIRT'
#  - '12' # a.k.a SAND

blocks:
  
  # Which block(s) can/cannot be placed while on duty. Can be either material name
  # (see http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html for list) or
  # material item ID number.
  place:
  #  - 'TNT'
  #  - 'BEDROCK'
  
  # Which block(s) can/cannot be broken while on duty. Can be either material name
  # (see http://jd.bukkit.org/rb/apidocs/org/bukkit/Material.html for list) or
  # material item ID number.
  break:
  #  - 'BEDROCK'

# Allow PvP while on duty?
allow-pvp: false

# Allow damaging mobs while on duty?
allow-mob-damage: false

# Allow interacting with the creative inventory while on duty? If this is set to
# false, no interaction with the player's inventory is allowed while on duty.
# This prevents the player from spawning in any creative items, but has the
# unfortunate side-effect of also preventing them from re-arranging their
# hotbar items.
allow-creative-inventory: false

# Allow interacting with inventories while on duty? If this is set to false, any
# sort of interaction with inventories (chests, furnaces, etc.) will be stopped.
allow-inventory-interaction: false

# Allow dropping items while on duty? If this is set to false, then the drops list
# above is ignored, and any dropping of items is stopped.
allow-item-drops: false

# Allow picking up items while on duty? If this is set to false, then the pickups list
# above is ignored, and any picking up of items is stopped.
allow-item-pickups: false

# Allow placing blocks while on duty? If this is set to false, then the place list
# above is ignored, and any placing of blocks is stopped.
allow-block-placing: false

# Allow breaking blocks while on duty? If this is set to false, then the break list
# above is ignored, and any breaking of blocks is stopped.
allow-block-breaking: false

# If you want to disallow specific commands when your players are on duty, specify
# them here. Leave out the first character (typically '/').
disallowed-commands:
#  - command1
#  - command2

# If you want to grant extra permissions when your players go on duty, specify them
# here. They will be removed again when the player goes off duty. These permissions
# are granted to players who have the doody.duty.extraperms.<listname> permission.
# A player can be given more than one set of extra permissions this way.
extra-permissions:
  mod: # Requires permission doody.duty.extraperms.mod
  #  - permission.for.one.thing
  #  - permission.for.something.else
  admin: # Requires permission doody.duty.extraperms.admin
  #  - a.permission.mods.dont.get
  #  - another.permission.mods.dont.get
  
# If you want your players to run commands when they go on duty, specify those here.
# If the command requires a certain permission to run, you can include it here, so
# that your players will have that command just for the purpose of running the command,
# and then it will be taken away from them again. Leave out the first character
# (typically '/'). These commands will be run for players who have the
# doody.duty.dutycommands.<listname> permission when they go on duty.
onduty-commands:
  mod:
  #  ignoreclaims:
  #    command: 'ignoreclaims'
  #    permissions: [griefprevention, griefprevention.ignoreclaims]
  #  dynmaphide:
  #    command: 'dynmap hide'
  #    permissions: [dynmap, dynmap.hide.self]
  admin:
  #  inspect:
  #    command: 'coreprotect inspect'
  #    permissions: [coreprotect, coreprotect.inspect]
  
# If you want your players to run commands when they go off duty, specify those here.
# If the command requires a certain permission to run, you can include it here, so
# that your players will have that command just for the purpose of running the command,
# and then it will be taken away from them again. If a permission is not needed, just
# leave out the permission altogether. In the command, you should leave out the first
# character (typically '/'). These commands will be run for players who have the
# doody.duty.dutycommands.<listname> permission when they go off duty.
offduty-commands:
  mod:
  #  ignoreclaims:
  #    command: 'ignoreclaims'
  #    permissions: [griefprevention, griefprevention.ignoreclaims]
  #  dynmapshow:
  #    command: 'dynmap show'
  #    permissions: [dynmap, dynmap.show.self]
  admin:
  #  inspect:
  #    command: 'coreprotect inspect'
  #    permissions: [coreprotect, coreprotect.inspect]
