name: OnDoOdy
website: http://dev.bukkit.org/bukkit-plugins/ondoody/
main: com.angelofdev.DoOdy.DoOdy
version: 1.0.0
description: >
             Separates a player's mod & admin duties so they too can enjoy the game.
author: alexschrod
authors: [angelofdev]
commands:
   ondoody:
      description: Puts players on duty mode.
      aliases: [doody, duty, dm]
      permission: doody.duty
      permission-message: You don't have the doody.duty permission
permissions:
   doody.*:
      description: Gives access to all OnDoOdy commands.
      children:
         doody.duty: true
         doody.reload: true
         doody.allowplace: true
         doody.allowbreak: true
         doody.dropitems: true
         doody.storage: true
         doody.pvp: true
         doody.mob: true
         doody.others: true
         doody.failsafe.bypass: true
         doody.debug: true
   doody.duty:
      description: Allows access to duty on/off commands
      default: op
   doody.reload:
      description: Allows in-game reloading of the configuration
      default: op
   doody.allowplace:
      description: Allows placing of blocks that are disallowed in configuration when on duty
      default: op
   doody.allowbreak:
      description: Allows breaking of blocks that are disallowed in configuration when on duty
      default: op
   doody.dropitems:
      description: Allows dropping of items from inventory when on duty
      default: op
   doody.pickupitems:
      description: Allows picking up items when on duty
      default: op
   doody.storage:
      description: Allows interaction with storage blocks when on duty
      default: op
   doody.pvp:
      description: Allows PvP while on duty
      default: op
   doody.mob:
      description: Allows attacking mobs while on duty
      default: op
   doody.others:
      description: Allows player to put another player on/off duty
      default: op
   doody.failsafe.bypass:
      description: Allows player to bypass doody's fail-safe
      default: op
   doody.debug:
      description: Enables access to debug commands
      default: op